
 *** Break *** segmentation violation
Loading HpsEvent Library from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
Event 10000
Event 20000
Event 30000
Event 40000
Event 50000
Event 60000
Event 70000
Event 80000
Event 90000
Event 100000
Event 110000
Event 120000
Event 130000
Event 140000
Event 150000
Event 160000
Event 170000
Event 180000
Event 190000
Event 200000
Event 210000
Event 220000
Event 230000
Event 240000
Event 250000
Event 260000
Event 270000
Event 280000
Event 290000
Event 300000
Event 310000
Event 320000
Event 330000
Event 340000
Event 350000
Event 360000
Event 370000
Event 380000
Event 390000
Event 400000
Event 410000
Event 420000
Event 430000
Event 440000
Event 450000
Event 460000
Event 470000
Event 480000
Event 490000
Event 500000
Event 510000
Event 520000
Event 530000
Event 540000
Event 550000
Event 560000
Event 570000
Event 580000
Event 590000
Event 600000
Event 610000
Event 620000
Event 630000
Event 640000
Event 650000
Event 660000
Event 670000
Event 680000
Event 690000
Event 700000
Event 710000
Event 720000
Event 730000
Event 740000
Event 750000
Event 760000
Event 770000
Event 780000
Event 790000
Event 800000
Event 810000
Event 820000
Event 830000
Event 840000
Event 850000
Event 860000
Event 870000
Event 880000
Event 890000
Event 900000
Event 910000
Event 920000
Event 930000
Event 940000
Event 950000
Event 960000
Event 970000
Event 980000
Event 990000
Event 1000000
Event 1010000
Event 1020000
Event 1030000
Event 1040000
Event 1050000
Event 1060000
Event 1070000
Event 1080000
Event 1090000
Event 1100000
Event 1110000
Event 1120000
Event 1130000
Event 1140000
Event 1150000
Event 1160000
Event 1170000
Event 1180000
Event 1190000
Event 1200000
Event 1210000
Event 1220000
Event 1230000
Event 1240000
Event 1250000
Event 1260000
Event 1270000
Event 1280000
Event 1290000
Event 1300000
Event 1310000
Event 1320000
Event 1330000
Event 1340000
Event 1350000
Event 1360000
Event 1370000
Event 1380000
Event 1390000
Event 1400000
Event 1410000
Event 1420000
Event 1430000
Event 1440000
Event 1450000
Event 1460000
Event 1470000
Event 1480000
Event 1490000
Event 1500000
Event 1510000
Event 1520000



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00002b3880b6c65e in waitpid () from /lib64/libc.so.6
#1  0x00002b3880afe609 in do_system () from /lib64/libc.so.6
#2  0x00002b3888de33f8 in TUnixSystem::StackTrace() () from /afs/slac/package/cernroot/53426/lib/libCore.so
#3  0x00002b3888de2273 in TUnixSystem::DispatchSignals(ESignals) () from /afs/slac/package/cernroot/53426/lib/libCore.so
#4  <signal handler called>
#5  0x00002b388d081a02 in HpsParticle::getCharge() const () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#6  0x00002b388d08734c in SvtTrack::getCharge() () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#7  0x00002b388d066d8e in G__HpsEventDic_203_0_21(G__value*, char const*, G__param*, int) () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#8  0x00002b388955d50f in Cint::G__CallFunc::Execute(void*) () from /afs/slac/package/cernroot/53426/lib/libCint.so
#9  0x00002b388890f427 in PyROOT::TIntExecutor::Execute(Cint::G__CallFunc*, void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#10 0x00002b388891582b in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::CallSafe(void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#11 0x00002b38889159b1 in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::Execute(void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#12 0x00002b38889131f6 in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::operator()(PyROOT::ObjectProxy*, _object*, _object*, long, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#13 0x00002b38889181a3 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#14 0x000000000041aac3 in PyObject_Call ()
#15 0x000000000048b614 in PyEval_EvalFrameEx ()
#16 0x000000000048d770 in PyEval_EvalFrameEx ()
#17 0x000000000048e269 in PyEval_EvalCodeEx ()
#18 0x000000000048e382 in PyEval_EvalCode ()
#19 0x00000000004a854c in run_mod ()
#20 0x00000000004a8620 in PyRun_FileExFlags ()
#21 0x00000000004a9b5c in PyRun_SimpleFileExFlags ()
#22 0x00000000004165b4 in Py_Main ()
#23 0x00002b3880aded5d in __libc_start_main () from /lib64/libc.so.6
#24 0x0000000000415599 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00002b388d081a02 in HpsParticle::getCharge() const () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#6  0x00002b388d08734c in SvtTrack::getCharge() () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
===========================================================


Traceback (most recent call last):
  File "tridentAnalysis_pass2.py", line 392, in <module>
    main()
  File "tridentAnalysis_pass2.py", line 242, in main
    if track.getCharge()>0 :
SystemError: problem in C++; program state has been reset

------------------------------------------------------------
Sender: LSF System <lsf@bullet0268>
Subject: Job 489808: <python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769> in cluster <slac> Exited

Job <python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769> was submitted from host <rhel6-64k> by user <mgraham> in cluster <slac>.
Job was executed on host(s) <bullet0268>, in queue <long>, as user <mgraham> in cluster <slac>.
</u/br/mgraham> was used as the home directory.
</u/br/mgraham/hps3/analysis/tridents> was used as the working directory.
Started at Fri Sep 25 06:08:47 2015
Results reported on Fri Sep 25 06:19:20 2015

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   402.31 sec.
    Max Memory :                                 4922 MB
    Average Memory :                             2461.30 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Processes :                              3
    Max Threads :                                4
    Run time :                                   634 sec.
    Turnaround time :                            634 sec.

The output (if any) is above this job summary.


 *** Break *** segmentation violation
Loading HpsEvent Library from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
Event 10000
Event 20000
Event 30000
Event 40000
Event 50000
Event 60000
Event 70000
Event 80000
Event 90000
Event 100000
Event 110000
Event 120000
Event 130000
Event 140000
Event 150000
Event 160000
Event 170000
Event 180000
Event 190000
Event 200000
Event 210000
Event 220000
Event 230000
Event 240000
Event 250000
Event 260000
Event 270000
Event 280000
Event 290000
Event 300000
Event 310000
Event 320000
Event 330000
Event 340000
Event 350000
Event 360000
Event 370000
Event 380000
Event 390000
Event 400000
Event 410000
Event 420000
Event 430000
Event 440000
Event 450000
Event 460000
Event 470000
Event 480000
Event 490000
Event 500000
Event 510000
Event 520000
Event 530000
Event 540000
Event 550000
Event 560000
Event 570000
Event 580000
Event 590000
Event 600000
Event 610000
Event 620000
Event 630000
Event 640000
Event 650000
Event 660000
Event 670000
Event 680000
Event 690000
Event 700000
Event 710000
Event 720000
Event 730000
Event 740000
Event 750000
Event 760000
Event 770000
Event 780000
Event 790000
Event 800000
Event 810000
Event 820000
Event 830000
Event 840000
Event 850000
Event 860000
Event 870000
Event 880000
Event 890000
Event 900000
Event 910000
Event 920000
Event 930000
Event 940000
Event 950000
Event 960000
Event 970000
Event 980000
Event 990000
Event 1000000
Event 1010000
Event 1020000
Event 1030000
Event 1040000
Event 1050000
Event 1060000
Event 1070000
Event 1080000
Event 1090000
Event 1100000
Event 1110000
Event 1120000
Event 1130000
Event 1140000
Event 1150000
Event 1160000
Event 1170000
Event 1180000
Event 1190000
Event 1200000
Event 1210000
Event 1220000
Event 1230000
Event 1240000
Event 1250000
Event 1260000
Event 1270000
Event 1280000
Event 1290000
Event 1300000
Event 1310000
Event 1320000
Event 1330000
Event 1340000
Event 1350000
Event 1360000
Event 1370000
Event 1380000
Event 1390000
Event 1400000
Event 1410000
Event 1420000
Event 1430000
Event 1440000
Event 1450000
Event 1460000
Event 1470000
Event 1480000
Event 1490000
Event 1500000
Event 1510000
Event 1520000



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00002ae4e242e65e in waitpid () from /lib64/libc.so.6
#1  0x00002ae4e23c0609 in do_system () from /lib64/libc.so.6
#2  0x00002ae4ea6a53f8 in TUnixSystem::StackTrace() () from /afs/slac/package/cernroot/53426/lib/libCore.so
#3  0x00002ae4ea6a4273 in TUnixSystem::DispatchSignals(ESignals) () from /afs/slac/package/cernroot/53426/lib/libCore.so
#4  <signal handler called>
#5  0x00002ae4ee942a02 in HpsParticle::getCharge() const () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#6  0x00002ae4ee94834c in SvtTrack::getCharge() () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#7  0x00002ae4ee927d8e in G__HpsEventDic_203_0_21(G__value*, char const*, G__param*, int) () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#8  0x00002ae4eae1f50f in Cint::G__CallFunc::Execute(void*) () from /afs/slac/package/cernroot/53426/lib/libCint.so
#9  0x00002ae4ea1d1427 in PyROOT::TIntExecutor::Execute(Cint::G__CallFunc*, void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#10 0x00002ae4ea1d782b in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::CallSafe(void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#11 0x00002ae4ea1d79b1 in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::Execute(void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#12 0x00002ae4ea1d51f6 in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::operator()(PyROOT::ObjectProxy*, _object*, _object*, long, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#13 0x00002ae4ea1da1a3 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#14 0x000000000041aac3 in PyObject_Call ()
#15 0x000000000048b614 in PyEval_EvalFrameEx ()
#16 0x000000000048d770 in PyEval_EvalFrameEx ()
#17 0x000000000048e269 in PyEval_EvalCodeEx ()
#18 0x000000000048e382 in PyEval_EvalCode ()
#19 0x00000000004a854c in run_mod ()
#20 0x00000000004a8620 in PyRun_FileExFlags ()
#21 0x00000000004a9b5c in PyRun_SimpleFileExFlags ()
#22 0x00000000004165b4 in Py_Main ()
#23 0x00002ae4e23a0d5d in __libc_start_main () from /lib64/libc.so.6
#24 0x0000000000415599 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00002ae4ee942a02 in HpsParticle::getCharge() const () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#6  0x00002ae4ee94834c in SvtTrack::getCharge() () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
===========================================================


Traceback (most recent call last):
  File "tridentAnalysis_pass2.py", line 392, in <module>
    main()
  File "tridentAnalysis_pass2.py", line 242, in main
    if track.getCharge()>0 :
SystemError: problem in C++; program state has been reset

------------------------------------------------------------
Sender: LSF System <lsf@hequ0025>
Subject: Job 500588: <python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769> in cluster <slac> Exited

Job <python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769> was submitted from host <rhel6-64k> by user <mgraham> in cluster <slac>.
Job was executed on host(s) <hequ0025>, in queue <long>, as user <mgraham> in cluster <slac>.
</u/br/mgraham> was used as the home directory.
</u/br/mgraham/hps3/analysis/tridents> was used as the working directory.
Started at Fri Sep 25 06:50:35 2015
Results reported on Fri Sep 25 07:03:01 2015

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   317.36 sec.
    Max Memory :                                 152 MB
    Average Memory :                             144.88 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   505 MB
    Max Processes :                              3
    Max Threads :                                4
    Run time :                                   746 sec.
    Turnaround time :                            747 sec.

The output (if any) is above this job summary.

Loading HpsEvent Library from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
Event 10000
Event 20000
Event 30000
Event 40000
Event 50000
Traceback (most recent call last):
  File "tridentAnalysis_pass2.py", line 393, in <module>
    main()
  File "tridentAnalysis_pass2.py", line 226, in main
    tree.GetEntry(entry)
KeyboardInterrupt

------------------------------------------------------------
Sender: LSF System <lsf@hequ0018>
Subject: Job 504928: <python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769> in cluster <slac> Exited

Job <python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769> was submitted from host <rhel6-64k> by user <mgraham> in cluster <slac>.
Job was executed on host(s) <hequ0018>, in queue <long>, as user <mgraham> in cluster <slac>.
</u/br/mgraham> was used as the home directory.
</u/br/mgraham/hps3/analysis/tridents> was used as the working directory.
Started at Fri Sep 25 07:08:16 2015
Results reported on Fri Sep 25 07:08:30 2015

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769
------------------------------------------------------------

TERM_OWNER: job killed by owner.
Exited with exit code 1.

Resource usage summary:

    CPU time :                                   11.55 sec.
    Max Memory :                                 62 MB
    Average Memory :                             62.00 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   493 MB
    Max Processes :                              3
    Max Threads :                                4
    Run time :                                   14 sec.
    Turnaround time :                            16 sec.

The output (if any) is above this job summary.


 *** Break *** segmentation violation
Loading HpsEvent Library from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
Event 10000
Event 20000
Event 30000
Event 40000
Event 50000
Event 60000
Event 70000
Event 80000
Event 90000
Event 100000
Event 110000
Event 120000
Event 130000
Event 140000
Event 150000
Event 160000
Event 170000
Event 180000
Event 190000
Event 200000
Event 210000
Event 220000
Event 230000
Event 240000
Event 250000
Event 260000
Event 270000
Event 280000
Event 290000
Event 300000
Event 310000
Event 320000
Event 330000
Event 340000
Event 350000
Event 360000
Event 370000
Event 380000
Event 390000
Event 400000
Event 410000
Event 420000
Event 430000
Event 440000
Event 450000
Event 460000
Event 470000
Event 480000
Event 490000
Event 500000
Event 510000
Event 520000
Event 530000
Event 540000
Event 550000
Event 560000
Event 570000
Event 580000
Event 590000
Event 600000
Event 610000
Event 620000
Event 630000
Event 640000
Event 650000
Event 660000
Event 670000
Event 680000
Event 690000
Event 700000
Event 710000
Event 720000
Event 730000
Event 740000
Event 750000
Event 760000
Event 770000
Event 780000
Event 790000
Event 800000
Event 810000
Event 820000
Event 830000
Event 840000
Event 850000
Event 860000
Event 870000
Event 880000
Event 890000
Event 900000
Event 910000
Event 920000
Event 930000
Event 940000
Event 950000
Event 960000
Event 970000
Event 980000
Event 990000
Event 1000000
Event 1010000
Event 1020000
Event 1030000
Event 1040000
Event 1050000
Event 1060000
Event 1070000
Event 1080000
Event 1090000
Event 1100000
Event 1110000
Event 1120000
Event 1130000
Event 1140000
Event 1150000
Event 1160000
Event 1170000
Event 1180000
Event 1190000
Event 1200000
Event 1210000
Event 1220000
Event 1230000
Event 1240000
Event 1250000
Event 1260000
Event 1270000
Event 1280000
Event 1290000
Event 1300000
Event 1310000
Event 1320000
Event 1330000
Event 1340000
Event 1350000
Event 1360000
Event 1370000
Event 1380000
Event 1390000
Event 1400000
Event 1410000
Event 1420000
Event 1430000
Event 1440000
Event 1450000
Event 1460000
Event 1470000
Event 1480000
Event 1490000
Event 1500000
Event 1510000
Event 1520000



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00002b228be7965e in waitpid () from /lib64/libc.so.6
#1  0x00002b228be0b609 in do_system () from /lib64/libc.so.6
#2  0x00002b22940f03f8 in TUnixSystem::StackTrace() () from /afs/slac/package/cernroot/53426/lib/libCore.so
#3  0x00002b22940ef273 in TUnixSystem::DispatchSignals(ESignals) () from /afs/slac/package/cernroot/53426/lib/libCore.so
#4  <signal handler called>
#5  0x00002b229838da02 in HpsParticle::getCharge() const () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#6  0x00002b229839334c in SvtTrack::getCharge() () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#7  0x00002b2298372d8e in G__HpsEventDic_203_0_21(G__value*, char const*, G__param*, int) () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#8  0x00002b229486a50f in Cint::G__CallFunc::Execute(void*) () from /afs/slac/package/cernroot/53426/lib/libCint.so
#9  0x00002b2293c1c427 in PyROOT::TIntExecutor::Execute(Cint::G__CallFunc*, void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#10 0x00002b2293c2282b in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::CallSafe(void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#11 0x00002b2293c229b1 in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::Execute(void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#12 0x00002b2293c201f6 in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::operator()(PyROOT::ObjectProxy*, _object*, _object*, long, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#13 0x00002b2293c251a3 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#14 0x000000000041aac3 in PyObject_Call ()
#15 0x000000000048b614 in PyEval_EvalFrameEx ()
#16 0x000000000048d770 in PyEval_EvalFrameEx ()
#17 0x000000000048e269 in PyEval_EvalCodeEx ()
#18 0x000000000048e382 in PyEval_EvalCode ()
#19 0x00000000004a854c in run_mod ()
#20 0x00000000004a8620 in PyRun_FileExFlags ()
#21 0x00000000004a9b5c in PyRun_SimpleFileExFlags ()
#22 0x00000000004165b4 in Py_Main ()
#23 0x00002b228bdebd5d in __libc_start_main () from /lib64/libc.so.6
#24 0x0000000000415599 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00002b229838da02 in HpsParticle::getCharge() const () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#6  0x00002b229839334c in SvtTrack::getCharge() () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
===========================================================


Traceback (most recent call last):
  File "tridentAnalysis_pass2.py", line 393, in <module>
    main()
  File "tridentAnalysis_pass2.py", line 242, in main
    if track.getCharge()>0 :
SystemError: problem in C++; program state has been reset

------------------------------------------------------------
Sender: LSF System <lsf@hequ0018>
Subject: Job 505073: <python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769> in cluster <slac> Exited

Job <python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769> was submitted from host <rhel6-64k> by user <mgraham> in cluster <slac>.
Job was executed on host(s) <hequ0018>, in queue <long>, as user <mgraham> in cluster <slac>.
</u/br/mgraham> was used as the home directory.
</u/br/mgraham/hps3/analysis/tridents> was used as the working directory.
Started at Fri Sep 25 07:08:41 2015
Results reported on Fri Sep 25 07:14:50 2015

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   303.23 sec.
    Max Memory :                                 152 MB
    Average Memory :                             143.15 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   505 MB
    Max Processes :                              3
    Max Threads :                                4
    Run time :                                   369 sec.
    Turnaround time :                            370 sec.

The output (if any) is above this job summary.


 *** Break *** segmentation violation
Loading HpsEvent Library from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
Event 10000
Event 20000
Event 30000
Event 40000
Event 50000
Event 60000
Event 70000
Event 80000
Event 90000
Event 100000
Event 110000
Event 120000
Event 130000
Event 140000
Event 150000
Event 160000
Event 170000
Event 180000
Event 190000
Event 200000
Event 210000
Event 220000
Event 230000
Event 240000
Event 250000
Event 260000
Event 270000
Event 280000
Event 290000
Event 300000
Event 310000
Event 320000
Event 330000
Event 340000
Event 350000
Event 360000
Event 370000
Event 380000
Event 390000
Event 400000
Event 410000
Event 420000
Event 430000
Event 440000
Event 450000
Event 460000
Event 470000
Event 480000
Event 490000
Event 500000
Event 510000
Event 520000
Event 530000
Event 540000
Event 550000
Event 560000
Event 570000
Event 580000
Event 590000
Event 600000
Event 610000
Event 620000
Event 630000
Event 640000
Event 650000
Event 660000
Event 670000
Event 680000
Event 690000
Event 700000
Event 710000
Event 720000
Event 730000
Event 740000
Event 750000
Event 760000
Event 770000
Event 780000
Event 790000
Event 800000
Event 810000
Event 820000
Event 830000
Event 840000
Event 850000
Event 860000
Event 870000
Event 880000
Event 890000
Event 900000
Event 910000
Event 920000
Event 930000
Event 940000
Event 950000
Event 960000
Event 970000
Event 980000
Event 990000
Event 1000000
Event 1010000
Event 1020000
Event 1030000
Event 1040000
Event 1050000
Event 1060000
Event 1070000
Event 1080000
Event 1090000
Event 1100000
Event 1110000
Event 1120000
Event 1130000
Event 1140000
Event 1150000
Event 1160000
Event 1170000
Event 1180000
Event 1190000
Event 1200000
Event 1210000
Event 1220000
Event 1230000
Event 1240000
Event 1250000
Event 1260000
Event 1270000
Event 1280000
Event 1290000
Event 1300000
Event 1310000
Event 1320000
Event 1330000
Event 1340000
Event 1350000
Event 1360000
Event 1370000
Event 1380000
Event 1390000
Event 1400000
Event 1410000
Event 1420000
Event 1430000
Event 1440000
Event 1450000
Event 1460000
Event 1470000
Event 1480000
Event 1490000
Event 1500000
Event 1510000
Event 1520000



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00002abc7385d65e in waitpid () from /lib64/libc.so.6
#1  0x00002abc737ef609 in do_system () from /lib64/libc.so.6
#2  0x00002abc7bad43f8 in TUnixSystem::StackTrace() () from /afs/slac/package/cernroot/53426/lib/libCore.so
#3  0x00002abc7bad3273 in TUnixSystem::DispatchSignals(ESignals) () from /afs/slac/package/cernroot/53426/lib/libCore.so
#4  <signal handler called>
#5  0x00002abc7fd71a02 in HpsParticle::getCharge() const () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#6  0x00002abc7fd7734c in SvtTrack::getCharge() () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#7  0x00002abc7fd56d8e in G__HpsEventDic_203_0_21(G__value*, char const*, G__param*, int) () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#8  0x00002abc7c24e50f in Cint::G__CallFunc::Execute(void*) () from /afs/slac/package/cernroot/53426/lib/libCint.so
#9  0x00002abc7b600427 in PyROOT::TIntExecutor::Execute(Cint::G__CallFunc*, void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#10 0x00002abc7b60682b in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::CallSafe(void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#11 0x00002abc7b6069b1 in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::Execute(void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#12 0x00002abc7b6041f6 in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::operator()(PyROOT::ObjectProxy*, _object*, _object*, long, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#13 0x00002abc7b6091a3 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#14 0x000000000041aac3 in PyObject_Call ()
#15 0x000000000048b614 in PyEval_EvalFrameEx ()
#16 0x000000000048d770 in PyEval_EvalFrameEx ()
#17 0x000000000048e269 in PyEval_EvalCodeEx ()
#18 0x000000000048e382 in PyEval_EvalCode ()
#19 0x00000000004a854c in run_mod ()
#20 0x00000000004a8620 in PyRun_FileExFlags ()
#21 0x00000000004a9b5c in PyRun_SimpleFileExFlags ()
#22 0x00000000004165b4 in Py_Main ()
#23 0x00002abc737cfd5d in __libc_start_main () from /lib64/libc.so.6
#24 0x0000000000415599 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00002abc7fd71a02 in HpsParticle::getCharge() const () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#6  0x00002abc7fd7734c in SvtTrack::getCharge() () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
===========================================================


Traceback (most recent call last):
  File "tridentAnalysis_pass2.py", line 393, in <module>
    main()
  File "tridentAnalysis_pass2.py", line 242, in main
    if track.getCharge()>0 :
SystemError: problem in C++; program state has been reset

------------------------------------------------------------
Sender: LSF System <lsf@bullet0126>
Subject: Job 507374: <python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769> in cluster <slac> Exited

Job <python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769> was submitted from host <rhel6-64k> by user <mgraham> in cluster <slac>.
Job was executed on host(s) <bullet0126>, in queue <long>, as user <mgraham> in cluster <slac>.
</u/br/mgraham> was used as the home directory.
</u/br/mgraham/hps3/analysis/tridents> was used as the working directory.
Started at Fri Sep 25 07:16:21 2015
Results reported on Fri Sep 25 07:32:43 2015

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   438.58 sec.
    Max Memory :                                 4223 MB
    Average Memory :                             2194.24 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Processes :                              7
    Max Threads :                                8
    Run time :                                   983 sec.
    Turnaround time :                            983 sec.

The output (if any) is above this job summary.


 *** Break *** segmentation violation
Loading HpsEvent Library from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
Event 10000
Event 20000



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00002ae3d8b6065e in waitpid () from /lib64/libc.so.6
#1  0x00002ae3d8af2609 in do_system () from /lib64/libc.so.6
#2  0x00002ae3e0dd73f8 in TUnixSystem::StackTrace() () from /afs/slac/package/cernroot/53426/lib/libCore.so
#3  0x00002ae3e0dd6273 in TUnixSystem::DispatchSignals(ESignals) () from /afs/slac/package/cernroot/53426/lib/libCore.so
#4  <signal handler called>
#5  0x00002ae3e5075a02 in HpsParticle::getCharge() const () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#6  0x00002ae3e507b34c in SvtTrack::getCharge() () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#7  0x00002ae3e505ad8e in G__HpsEventDic_203_0_21(G__value*, char const*, G__param*, int) () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#8  0x00002ae3e155150f in Cint::G__CallFunc::Execute(void*) () from /afs/slac/package/cernroot/53426/lib/libCint.so
#9  0x00002ae3e0903427 in PyROOT::TIntExecutor::Execute(Cint::G__CallFunc*, void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#10 0x00002ae3e090982b in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::CallSafe(void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#11 0x00002ae3e09099b1 in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::Execute(void*, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#12 0x00002ae3e09071f6 in PyROOT::TMethodHolder<PyROOT::TScopeAdapter, PyROOT::TMemberAdapter>::operator()(PyROOT::ObjectProxy*, _object*, _object*, long, bool) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#13 0x00002ae3e090c1a3 in PyROOT::(anonymous namespace)::mp_call(PyROOT::MethodProxy*, _object*, _object*) () from /afs/slac/package/cernroot/53426/lib/libPyROOT.so
#14 0x000000000041aac3 in PyObject_Call ()
#15 0x000000000048b614 in PyEval_EvalFrameEx ()
#16 0x000000000048d770 in PyEval_EvalFrameEx ()
#17 0x000000000048e269 in PyEval_EvalCodeEx ()
#18 0x000000000048e382 in PyEval_EvalCode ()
#19 0x00000000004a854c in run_mod ()
#20 0x00000000004a8620 in PyRun_FileExFlags ()
#21 0x00000000004a9b5c in PyRun_SimpleFileExFlags ()
#22 0x00000000004165b4 in Py_Main ()
#23 0x00002ae3d8ad2d5d in __libc_start_main () from /lib64/libc.so.6
#24 0x0000000000415599 in _start ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00002ae3e5075a02 in HpsParticle::getCharge() const () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
#6  0x00002ae3e507b34c in SvtTrack::getCharge() () from /nfs/slac/g/hps3/software/hps-dst/build/lib/libHpsEvent.so
===========================================================


Traceback (most recent call last):
  File "tridentAnalysis_pass2.py", line 393, in <module>
    main()
  File "tridentAnalysis_pass2.py", line 242, in main
    if track.getCharge()>0 :
SystemError: problem in C++; program state has been reset

------------------------------------------------------------
Sender: LSF System <lsf@bullet0191>
Subject: Job 523414: <python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769> in cluster <slac> Exited

Job <python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769> was submitted from host <rhel6-64k> by user <mgraham> in cluster <slac>.
Job was executed on host(s) <bullet0191>, in queue <long>, as user <mgraham> in cluster <slac>.
</u/br/mgraham> was used as the home directory.
</u/br/mgraham/hps3/analysis/tridents> was used as the working directory.
Started at Fri Sep 25 08:16:21 2015
Results reported on Fri Sep 25 08:17:05 2015

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python tridentAnalysis_pass2.py -o OutputHistograms/Data/pass2/hps_005769_09252015.root pass2-dst/hps_005769
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   46.31 sec.
    Max Memory :                                 308 MB
    Average Memory :                             36.00 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Processes :                              3
    Max Threads :                                4
    Run time :                                   46 sec.
    Turnaround time :                            46 sec.

The output (if any) is above this job summary.

